---
title: "Projet"
author: "Mai Chi Do, Heloise ROZIER, Romane LE GOFF"
date: "10/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
library(sf)
library(dplyr)
library(tidyverse)
# Pour les modeles d'econometrie spatiale
library(spdep)
#Pour le calcul de distance (fonction rdist)
library(fields)
#Pour la lecture de table SAS (fonction read.sas7bdat)
library(sas7bdat)
# Pour la cartographie
library(RColorBrewer)
library(classInt)
library(Guerry)
library(GISTools)
library(sp)
```

# Importation des données

```{r}
data(gfrance85)
```

# Cartographie

```{r}
my.palette <- brewer.pal(n = 7, name = "OrRd")

spplot(gfrance85,"Crime_pers", col.regions = my.palette, cuts = 6, col = "transparent", main="Nombre de crimes contre des personnes en France (1833)")
```

# Calculer des centroides des departements

```{r}
centroids <- coordinates(gfrance85)
```

# Matrice de contiguité

## Definition de voisins

```{r}
voisins <- poly2nb(gfrance85)
summary(voisins)
```

`r gfrance85$Department[c(22,26,54,59,63,65,70)] ` sont les départements les plus isolés, tandis que `r gfrance85$Department[46] ` et `r gfrance85$Department[72] `
les plus connectées.

## Matrice de contiguité

```{r}
### Matrice de contiguite standardisee en ligne, methode par defaut
cont.w <- nb2listw(voisins,style="W")

### Plus proches voisins
### Definition des 2 plus proches voisins
#   k indique le nombre de voisins
cartePPV2.knn <- knearneigh(centroids,k=2) 
cartePPV2.nb  <- knn2nb(cartePPV2.knn)
PPV2.w<-nb2listw(cartePPV2.nb,style="W") # Matrice de voisinage des 2 ppv

### Definition des 5 plus proches voisins
cartePPV5.knn<-knearneigh(centroids,k=5) 
cartePPV5.nb<- knn2nb(cartePPV5.knn)
PPV5.w<-nb2listw(cartePPV5.nb,style="W")

### Autre option
##basee sur la distance avec des coordonnees ------------------------------------------------------------------------
# wd5 <- dnearneigh(centro, 0, 5)
## en km si true

### Matrice de voisinage fondee sur la distance euclidienne
distance<-rdist(centroids) 
# permet de calculer la dist entre tous les individus en fct de leurs coordonnees
# voir aussi fonction "dist" pour d'autres distances

diag(distance)<-0
## rayon de 100 km
distance[distance>=100000 ]<-0
dist<- 1.e6 / (distance*distance) #inverse de la dist au carre
dist[dist>1.e9]<-0
dist.w<-mat2listw(dist, row.names = NULL, style="W")
```
## Autocorrélation spatiale

```{r}
### Test de Moran, Donnees Brutes
moran.test(gfrance85$Crime_pers, dist.w, zero.policy=TRUE) # permet de recup la stat de Moran
#I de Moran = 5.2661

### Graphique de Moran
moran.plot(x=gfrance85$Crime_pers,dist.w,xlab="Criminalite France 1833",
           ylab="Taux dans le voisinage",
           zero.policy=TRUE)
```

